config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  root to: 'pages#home'
  resources :profiles, only: %i[show new create update edit] do
    resources :performances, only: %i[new create] do
      resources :bookings, only: %i[new create]
    end
  end
  resources :bookings, only: %i[update show]
  resources :performances, only: %i[show edit update] do
    resources :reviews, only: :create
  end

  patch "/performances/toggle/:id", to: "performances#toggle", as: "performance_toggle"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :avatar_url, PhotoUploader
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :address_zipcode, presence: true
  validates :address_city, presence: true
  validates :address_country, presence: true
  # voir pour affichage if il est performeur - validates :performer_description
  belongs_to :user, dependent: :destroy
  has_many :bookings
  has_many :performances
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :reviews
  def notification
    my_bookings = self.bookings.where(status: "waiting for payment").size
    bookings = Booking.joins("INNER JOIN performances ON performances.id = bookings.performance_id").where("bookings.status = 'on demand' AND performances.profile_id=?", self.id).size
    my_bookings + bookings
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @review = Review.new
    @profile = current_user.profile
    # recuperation des performances prose par le current user
    @performances = Performance.where(profile_id: @profile.id)
    @nbr_performances = @performances.size

    # recuperation des bookings pour le current user
    # @cocktails = Cocktail.joins(doses: :ingredient).where("ingredients.name LIKE ?", "%#{params[:ingredient].capitalize}%")
    @bookings = Booking.joins("INNER JOIN performances ON performances.id = bookings.performance_id").where("performances.profile_id=?", @profile.id).order(:start)
    @nbr_bookings = @bookings.size

    # recuperation des bookings faite par le current user
    @my_bookings = Booking.where(profile_id: @profile.id)
    @nbr_my_bookings = @my_bookings.size
    if params[:format]
      @page = params[:format]
    else
      if @nbr_performances != 0
        @page = "1"
      else
        @page = "3"
      end
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  private

  def profile_params
    params.require(:profile).permit(:last_name, :first_name, :address, :address_city, :address_zipcode, :address_country, :performer_description, :avatar_url)
  end
end

app/views/profiles/_card_booking.html.erb
<% count = 0 %>
<% @bookings.each do |booking| %>
  <% if booking.status.split(' ')[0] != "cancelled" && booking.status != "performed"%>
    <% count += 1 %>
    <div class="card-product">
      <%= cl_image_tag booking.performance.photo, height: 300, width: 400, crop: :fill %> 
      <div class="card-product-infos">
        <h2><%= link_to "#{booking.performance.title}", performance_path(booking.performance.id) %></h2>
        <p><%= booking.performance.description %> </p>
        <% if booking.start %>
          <p><strong>Date : </strong><%=booking.start.to_time.strftime('%d-%m-%y')%> at <%=booking.end.to_time.strftime('%d-%m-%y')%></p>
        <% end %> 
      </div>
      <div class="card-product-status text-center">
        <% if booking.status == "waiting for payment" || booking.status.split(' ')[0] == "cancelled" || booking.status == "performed" || booking.status == "payed"%>
          <p><strong><%= booking.status.capitalize %></strong></p>
        <% end %>
        <% if booking.status == "on demand" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "waiting for payment"%>
            <%= f.submit "Vadidate", class: "btn-profile-card btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
        <% if booking.status.split(' ')[0] != "cancelled" && booking.status != "performed"%>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "cancelled by performer"%>
            <%= f.submit "Cancel", class: "btn-profile-card btn btn-danger btn-sm" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
<% if count == 0 %>
  Pas de performance en attente !
<% end %>

app/views/profiles/_card_booking_done.html.erb
<% @bookings.each do |booking| %>
  <% if booking.status.split(' ')[0] == "cancelled" || booking.status == "performed"%>
    <div class="card-product card-disable">
      <%= cl_image_tag booking.performance.photo, height: 300, width: 400, crop: :fill %> 
      <div class="card-product-infos">
        <h2><%= link_to "#{booking.performance.title}", performance_path(booking.performance.id) %></h2>
        <p><%= booking.performance.description %> </p>
        <% if booking.start %>
          <p><strong>Date : </strong><%=booking.start.to_time.strftime('%d-%m-%y')%> at <%=booking.end.to_time.strftime('%d-%m-%y')%></p>
        <% end %>
      </div>
      <div class="card-product-status text-center">
        <% if booking.status == "waiting for payment" || booking.status.split(' ')[0] == "cancelled" || booking.status == "performed"%>
          <p><strong><%= booking.status.capitalize %></strong></p>
        <% end %>
        <% if booking.status == "on demand" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "waiting for payment"%>
            <%= f.submit "Vadidate", class: "btn-profile-card btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
        <% if booking.status.split(' ')[0] != "cancelled" && booking.status != "performed"%>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "cancelled by performer"%>
            <%= f.submit "Cancel", class: "btn-profile-card btn btn-danger btn-sm" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/profiles/_card_my_bookings.html.erb
<% count = 0 %>
<% @my_bookings.each do |booking| %>
  <% if booking.status.split(' ')[0] != "cancelled" && booking.status != "performed" %>
  <% count += 1 %>
    <div class="card-product">
      <%= cl_image_tag booking.performance.photo %> 
      <div class="card-product-infos">
        <h2><%= link_to "#{booking.performance.title}", performance_path(booking.performance.id) %></h2>
        <p><%= booking.performance.description %> </p>
        <% if booking.start %>
          <p><strong>Date : </strong><%=booking.start.to_time.strftime('%d-%m-%y')%> at <%=booking.end.to_time.strftime('%d-%m-%y')%></p>
        <% end %>
      </div>
      <div class="card-product-status text-center">
        <% if booking.status == "payed" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "performed"%>
            <%= f.submit "Performed ?", class: "btn-profile-card btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
        <% if booking.status == "waiting for payment" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "payed"%>
            <%= f.submit "Checkout", class: "btn-profile-card btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
        <% if booking.status == "on demand" || booking.status.split(' ')[0] == "cancelled" || booking.status == "performed"%>
          <p><strong><%= booking.status.capitalize %></strong></p>
        <% end %>
        <% if booking.status.split(' ')[0] != "cancelled" && booking.status != "performed" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "cancelled by user"%>
            <%= f.submit "Cancel", class: "btn-profile-card btn btn-danger btn-sm" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>



<% if count == 0 %>
  Vous n'attendez aucun artist !
<% end %>

app/views/profiles/_card_my_bookings_done.html.erb
<hr>
<% @my_bookings.each do |booking| %>
  <% if booking.status.split(' ')[0] == "cancelled" || booking.status == "performed" %>
    <div class="card-product card-disable">
      <%= cl_image_tag booking.performance.photo %> 
      <div class="card-product-infos">
        <h2><%= link_to "#{booking.performance.title}", performance_path(booking.performance.id) %></h2>
        <p><%= booking.performance.description %> </p>
        <% if booking.start %>
          <p><strong>Date : </strong><%=booking.start.to_time.strftime('%d-%m-%y')%> at <%=booking.end.to_time.strftime('%d-%m-%y')%></p>
        <% end %>
      </div>
      <div class="card-product-status text-center">
        <% if booking.status == "payed" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "performed"%>
            <%= f.submit "Performed ?", class: "btn-profile-card btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
        <% if booking.status == "waiting for payment" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "payed"%>
            <%= f.submit "Checkout", class: "btn-profile-card btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
        <% if booking.status == "on demand" || booking.status.split(' ')[0] == "cancelled" || booking.status == "performed"%>
          <p><strong><%= booking.status.capitalize %></strong></p>
        <% end %>
        <% if booking.status.split(' ')[0] != "cancelled" && booking.status != "performed" %>
          <%= simple_form_for booking, :url => booking_path(booking.id), :method => :PATCH do |f| %>
            <%= f.hidden_field :status, value: "cancelled by user"%>
            <%= f.submit "Cancel", class: "btn-profile-card btn btn-danger btn-sm" %>
          <% end %>
        <% end %>

        <% if booking.status == "performed" %>
          <button type="button" class="btn-profile-card btn btn-primary btn-sm" data-toggle="modal" data-target="#reviewModal-<%= booking.performance.id %>">
            Add review
            
          </button>
        <% end %>
      </div>
    </div>
  <% end %>
  <!-- Modal -->
  <div class="modal fade" id="reviewModal-<%= booking.performance.id %>" tabindex="-1" role="dialog" aria-labelledby="reviewModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="reviewModalLabel">Add review for <%= booking.performance.title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for([booking.performance, @review]) do |f| %>
            <%= f.input :content %>
            <%= f.input :note, collection: 0..5 %>
            <%= f.submit "Add a review", class: "btn btn-success btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-sm-4 offset-md-4">
    <h2>Update your profile</h2>
    <%= simple_form_for(@profile) do |f| %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :address %>
          <%= f.input :address_zipcode %>
          <%= f.input :address_city %>
          <%= f.input :address_country, priority: ["FR", "BE", "DE"] %>
          <%= f.input :performer_description %>
          <%= f.input :avatar_url, as: :file %>
          <%= f.input :avatar_url_cache, as: :hidden %>
          <%= f.submit "Update profile", class: "btn btn-primary btn-block" %>
      <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-sm-4 offset-md-4">
    <h2>Complited your profile</h2>
    <%= simple_form_for(@profile) do |f| %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :address %>
          <%= f.input :address_zipcode %>
          <%= f.input :address_city %>
          <%= f.input :address_country, priority: ["FR", "BE", "DE"] %>
          <%= f.input :performer_description %>
          <%= f.input :avatar_url, as: :file %>
          <%= f.input :avatar_url_cache, as: :hidden %>
          <%= f.submit "Update profile", class: "btn btn-primary btn-block" %>
      <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <h2>Welcome <%= @profile.first_name %> <%= @profile.last_name %></h2>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <% if @nbr_performances != 0 %>
      <li class="nav-item">
        <a class="nav-link <%= "active" if @page == "1" %>" id="catalogue-tab" data-toggle="tab" href="#catalogue" role="tab" aria-controls="catalogue" aria-selected="true">Mon catalogue (<%= @nbr_performances %>)</a>
      </li>
    <% end %>
    <% if @nbr_bookings != 0 %> 
      <li class="nav-item">
        <a class="nav-link <%= "active" if @page == "2" %>" id="performance-tab" data-toggle="tab" href="#performance" role="tab" aria-controls="performance" aria-selected="false">Mes performances à réaliser (<%= @nbr_bookings %>)</a> 
      </li>
    <% end %>
    <% if @nbr_my_bookings != 0 %>
      <li class="nav-item">
        <a class="nav-link  <%= "active" if @page == "3" %>" id="booking-tab" data-toggle="tab" href="#booking" role="tab" aria-controls="booking" aria-selected="false">Mes réservations (<%= @nbr_my_bookings %>)</a>
      </li>
    <% end %>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade <%= "show active" if @page == "1" %>" id="catalogue" role="tabpanel" aria-labelledby="catalogue-tab">
      <div class="row">
        <div class="col">
          <% @performances.each do |performance| %>
            <div class="card-product">
            
              <% if (performance.photo.url.nil?)  %>
               <%= cl_image_tag 'illus_default.jpg' %> 
              <% else %>
                <%= cl_image_tag performance.photo %> 
              <% end %>

              <div class="card-product-infos">
                <h2><%= link_to "#{performance.title}", performance_path(performance.id) %></h2>
                <p><%= performance.description %> </p>
                <div class="card-product-controler">
                  <%= link_to edit_performance_path(performance.id) do %>
                    <i class="fas fa-pen"></i>
                  <% end %>
                </div>
              </div>
              <div class="card-product-status text-center">
                <% if performance.active %>
                  <%= link_to "Disable", performance_toggle_path(performance), method: :patch, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to "Enable", performance_toggle_path(performance), method: :patch, class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade <%= "show active" if @page == "2" %>" id="performance" role="tabpanel" aria-labelledby="performance-tab">
      <div class="row">
        <div class="col">
          <%= render "card_booking" %>
          <hr>
          <%= render "card_booking_done" %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade <%= "show active" if @page == "3" %>" id="booking" role="tabpanel" aria-labelledby="booking-tab">
      <div class="row">
        <div class="col">
          <%= render "card_my_bookings" %>
          
          <%= render "card_my_bookings_done" %>
        </div>
      </div>
    </div>
  </div>

  <div class="text-right">
    <%= link_to "Create a new performance", new_profile_performance_path(@profile.id), class:"btn btn-primary" %>
  </div>
</div>