config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  root to: 'pages#home'
  resources :profiles, only: %i[show new create update edit] do
    resources :performances, only: %i[new create] do
      resources :bookings, only: %i[new create]
    end
  end
  resources :bookings, only: %i[update show]
  resources :performances, only: %i[show edit update] do
    resources :reviews, only: :create
  end

  patch "/performances/toggle/:id", to: "performances#toggle", as: "performance_toggle"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/performance.rb
class Performance < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  
  validates :title, presence: true
  validates :description, presence: true
  validates :hour_price, presence: true

  belongs_to :category
  belongs_to :profile
  has_many :booking

  include PgSearch
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true } 
    }

  has_many :review

  def average_rating
    rate = self.review.average(:note)
    if rate
      return rate.round(2)
    else
      return "-"
    end
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :find_profile, only: [ :new, :create]

  def show
    @performance = Performance.find(params[:id])
    if user_signed_in?
      @distance = Geocoder::Calculations.distance_between([@performance.profile.latitude, @performance.profile.longitude], [current_user.profile.latitude, current_user.profile.longitude]) 
      @booking = Booking.new
      @dates_booked_array = dates_booked
    else
      @distance = 0
    end
  end

  def new
    @performance = Performance.new
  end

  def create
    @performance = Performance.new(performance_params)
    @performance.profile = @profile
    @performance.save
    redirect_to profile_path(@profile.id)
  end

  def edit
    @performance = Performance.find(params[:id])
  end

  def update
    @performance = Performance.find(params[:id])
    @performance.update(performance_params)
    redirect_to profile_path(@performance.profile.id)
  end

  def toggle
    @performance = Performance.find(params[:id])
    if @performance.active
      @performance.active = false
    else
      @performance.active = true
    end
    @performance.save
    redirect_to profile_path(@performance.profile.id)
  end

  private

  def dates_booked
    dates_booked_array = []
    @dates = Booking.where("NOT status = 'performed' AND performance_id = ?", @performance.id).pluck(:start, :end)
    @dates.each do |couple_date|
      (couple_date[0]..couple_date[1]).each do |date|
        dates_booked_array << date.to_s
      end
    end
    dates_booked_array
  end

  def performance_params
    params.require(:performance).permit(:title, :description, :category_id, :photo, :photo_cache, :performance_date_id, :profile_id, :start_date, :end_date, :hour_price)
  end

  def find_profile
    @profile = Profile.find(params[:profile_id])
  end
end

app/views/performances/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-md-3">
      <h1>Modify a performance</h1>
      <%= simple_form_for [@profile, @performance] do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :hour_price %>
        <%= f.input :category_id, collection: Category.all %>
        <%= f.submit "validate changes", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/performances/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-md-3">
      <h1>Create a new performance</h1>
      <%= simple_form_for [@profile, @performance] do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :hour_price%>
        <%= f.input :category_id, collection: Category.all %>
        <%= f.submit "add a performance", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/performances/show.html.erb
<div class="banner-performance" style = "background-image: url(
  <% if @performance.photo.url.nil? %>
    <%= cl_image_path('illus_default.jpg')%>
  <% else %>
    <%= cl_image_path(@performance.photo)%>
  <% end %>
  )">
</div>
<div class="container relat">
  <div class="container abso">
    <div class="row">
      <div class="col">
        <div class="title-image-performance-card">
          <% if @performance.photo.url.nil? %>
            <%= cl_image_tag('illus_default.jpg', width: 400, height: 300, crop: :fill )%>
          <% else %>
            <%= cl_image_tag(@performance.photo, width: 400, height: 300, crop: :fill )%>
          <% end %>

          <div class="text-left">
            <h1><%= @performance.title %></h1>
            <h3>Catégorie : <%= @performance.category.name %></h3>
            <p>Review : <span style="color:#e7a117"><% rate = @performance.average_rating %>
              <% if rate != '-' %>
                <%= rate > 0.5 ? icon('fas', 'star') : icon('far', 'star') %>
                <%= rate > 1.5 ? icon('fas', 'star') : icon('far', 'star') %>
                <%= rate > 2.5 ? icon('fas', 'star') : icon('far', 'star') %>
                <%= rate > 3.5 ? icon('fas', 'star') : icon('far', 'star') %>
                <%= rate > 4.5 ? icon('fas', 'star') : icon('far', 'star') %>
              <% end %>
              </span>
            </p>
            <p><%=  @performance.description.capitalize %></p>
            <p> <%= @performance.hour_price %> € per hour</p>

          </div>
        </div>
      </div>
    </div>

    <div id="calendar-flatpickr" class="calendar">
      <div class="row">

        <% if user_signed_in? %>
          <% unless @performance.profile == current_user.profile %>
            <%= simple_form_for @booking, html: {class: 'form-inline'}, :url => profile_performance_bookings_path(current_user.profile.id, @performance.id), :method => :POST do |f| %>
              <div class="col-sm-4">
                <%= "Start date" %>
                <%= f.input_field :start, as: :string, value: "Start date"%>
              </div>
              <div class="col-sm-4 offset-sm-1">
                <%= "End date" %>
                <%= f.hidden_field :end, as: :string, value: "End date" %> 
              </div>
              <div class="col-sm-2 offset-sm-1">
                <%= f.submit "Booking" %>
              </div>
            <% end %>
          <% else %>
          <% end %>

        <% else %>
          <div class="col-sm-6 align-middle">
            <p>Consultez les disponibilités de nos meilleurs artistes en vous inscrivant : </p>
          </div>
          <div class="col-sm-4 align-middle">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

  <div id="dates" data-list="<%=@dates_booked_array.to_json%>"></div>
</div>